version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - "5678:5432"
    environment:
      POSTGRES_USER: asyarif
      POSTGRES_PASSWORD: he4vyR0ad$
      POSTGRES_DB: dedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=6553kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"

  redis:
    image: redis:6
    ports:
      - "3456:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
