services:
  postgres:
    restart: always
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"

  redis:
    image: redis:6
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  postgres-exporter:
    image: bitnami/postgres-exporter:0.15.0
    restart: always
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/?sslmode=disable
    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.52.0
    restart: always
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.0.0
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: ${POSTGRES_DB}
      GF_DATABASE_USER: ${POSTGRES_USER}
      GF_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
