global:
  # DO NOT use this value in production, it's only for demo purposes
  # I usually use around 15s or 30s value
  scrape_interval: 30s
scrape_configs:
  - job_name: "iuranorg-api"
    static_configs:
      - targets:
          - 103.127.96.200:8081
  - job_name: "postgres"
    static_configs:
      - targets:
          - postgres-exporter:9187
